version: "2.2"

networks:
  mifos:
    driver: bridge
services:
  mifos-credito-simple-se:
    image: harbor.infotec.mx/mifosio/com.mx.infotec.fineract.cn.creditosimple.se.preproduccion
    mem_limit: 2048m
    volumes:
      - /opt/mifosio/certificates/bambi.pem:/usr/local/lsws/admin/conf/webadmin.crt
      - /opt/mifosio/certificates/bambi.key:/usr/local/lsws/admin/conf/webadmin.key
    restart: always
    extra_hosts:
      - "eureka:172.22.216.195"
      - "cassandra:172.22.216.198"
      - "tidb:172.22.216.197"
      - "activemq:172.22.216.196"    
    healthcheck:
      test: ["CMD", "curl", "-k", "https://127.0.0.1:8443"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8443:443"
      - "80:80"
      - "61616:61616"
      - "7090:7080"
    networks:
      - mifos
