version: "2.2"

networks:
  mifos:
    driver: bridge
services:
  infotec-bancodelbienestar-originacion:
    image: harbor.infotec.mx/mifosio/com.mx.infotec.fineract.cn.creditosimple.se.develop
    mem_limit: 2048m
    volumes:
      - /home/dads/certificates/bundle.crt:/etc/ssl/certs/fullchain.pem
      - /home/dads/certificates/infotec_2019.key:/etc/ssl/private/privkey.pem
    restart: always
    extra_hosts:
      - "eureka:172.22.216.195"
      - "cassandra:172.22.216.198"
      - "tidb:172.22.216.197"
      - "activemq:172.22.216.196"    
    healthcheck:
      test: ["CMD", "curl", "--fail", "https://127.0.0.1:61616"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "61616:61616"
    networks:
      - mifos     
