version: "2.2"

networks:
  mifos:
    driver: bridge
services:
  mifos-credito-simple-se:
    image: harbor.infotec.mx/mifosio/com.mx.infotec.fineract.cn.creditosimple.se.develop
    mem_limit: 2048m
    volumes:
      - /home/dads/certificates/bundle.crt:/etc/ssl/certs/fullchain.pem
      - /home/dads/certificates/infotec_2019.key:/etc/ssl/private/privkey.pem
    restart: always    
    healthcheck:
      test: ["CMD", "curl", "-k --fail", "https://127.0.0.1:443"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "443:443"
    networks:
      - mifos     
