version: "2.2"

networks:
  mifos:
    driver: bridge
services:
  mifos-credito-simple-se:
    image: harbor.infotec.mx/mifosio/com.mx.infotec.fineract.cn.creditosimple.se.develop
    mem_limit: 2048m
    volumes:
      - /home/dads/certificates/bundle.crt:/etc/ssl/certs/fullchain.pem
      - /home/dads/certificates/infotec_2019.key:/etc/ssl/private/privkey.pem
    restart: always    
    ports:
      - "8443:8443"
    networks:
      - mifos     
